name: Update Ostluft Data Daily

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 05:00 UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.4.3
    env:
      CI_COMMIT_MESSAGE: "GH Actions: Daily Data Update"
      CI_COMMIT_AUTHOR: "github-actions"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Run the data update script
        run: Rscript update_data.R

      - name: Commit and push updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: |
          git config --global user.name "${CI_COMMIT_AUTHOR}"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add data/ostluft/*.rds
          git commit -m "${CI_COMMIT_MESSAGE}" || echo "No changes to commit"
          git push
